# Generated by Django 5.1.4 on 2025-03-11 05:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_ATTEMPT', 'Login Attempt'), ('FAILED_LOGIN', 'Failed Login'), ('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_LOCKED', 'Account Locked'), ('MULTIPLE_IP', 'Multiple IPs Used'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
