# Generated by Django 5.1.4 on 2025-03-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_securitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitylog',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('FAILED_LOGIN', 'Failed Login'), ('LOGIN', 'Login'), ('PASSWORD_RESET', 'Password Reset')], max_length=50),
        ),
    ]
