# Generated by Django 5.1.4 on 2025-03-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_securitylog_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
