# Generated by Django 5.1.4 on 2025-03-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_is_blacklisted'),
        ('core', '0004_securitylog_additional_info_securitylog_user_agent'),
    ]

    operations = [
    ]
