# Generated by Django 5.1.4 on 2025-03-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
