# Generated by Django 5.1.4 on 2025-03-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
            ],
            options={
                'verbose_name': 'Sales Report',
                'verbose_name_plural': 'Sales Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.customuser',),
        ),
        migrations.CreateModel(
            name='UserEngagementReport',
            fields=[
            ],
            options={
                'verbose_name': 'User Engagement Report',
                'verbose_name_plural': 'User Engagement Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.customuser',),
        ),
    ]
