# Generated by Django 5.1.4 on 2025-03-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_salesreport_userengagementreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionPerformance',
            fields=[
            ],
            options={
                'verbose_name': 'Auction Performance',
                'verbose_name_plural': 'Auction Performance Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.customuser',),
        ),
    ]
