# Generated by Django 5.1.4 on 2025-02-27 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_name_172c3e_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('selling', 'Selling'), ('renting', 'Renting'), ('auction', 'Auction')], db_index=True, default='selling', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'description', 'additional_information', 'price', 'discount', 'availability', 'sku', 'size', 'image', 'features', 'categories', 'stock', 'brand', 'product_type'], name='shop_produc_name_03485c_idx'),
        ),
    ]
