# Generated by Django 5.1.4 on 2025-03-01 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_user_alter_order_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='shop_order_product_f27cc4_idx',
            old_name='shop_order_product_6cdb5a_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
