# Generated by Django 5.1.4 on 2025-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('win', 'Auction Win'), ('outbid', 'Outbid Alert'), ('ending_soon', 'Ending Soon Alert')], default='win', max_length=20),
        ),
    ]
