# Generated by Django 5.1.4 on 2025-03-09 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDropSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_name_03485c_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('win', 'Auction Win'), ('outbid', 'Outbid Alert'), ('ending_soon', 'Ending Soon Alert'), ('price_drop', 'Price Drop Alert')], default='win', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'description', 'additional_information', 'price', 'availability', 'sku', 'size', 'image', 'features', 'categories', 'stock', 'brand', 'product_type'], name='shop_produc_name_d25063_idx'),
        ),
        migrations.AddField(
            model_name='pricedropsubscription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_drop_subscribers', to='shop.product'),
        ),
        migrations.AddField(
            model_name='pricedropsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_drop_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pricedropsubscription',
            unique_together={('user', 'product')},
        ),
    ]
