# Generated by Django 5.1.4 on 2025-04-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_bidorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidorder',
            name='payment_status',
            field=models.CharField(choices=[('Cash on Delevery', 'Cash on Delevery'), ('Khalti', 'Khalti')], default='Cash on Delevery', max_length=255),
        ),
        migrations.AlterField(
            model_name='bidorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
