# Generated by Django 5.1.4 on 2025-04-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_bidorder_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidorder',
            name='payment_status',
            field=models.CharField(choices=[('Cash on Delevery', 'Cash on Delevery'), ('Khalti', 'Khalti')], default='Cash on Delevery', max_length=255),
        ),
    ]
