# Generated by Django 5.1.4 on 2025-04-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_bidorder_payment_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='shop_brand_name_c466ec_idx',
        ),
        migrations.AlterField(
            model_name='bidorder',
            name='payment_status',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('Cash on Delevery', 'Cash on Delevery')], default='Cash on Delevery', max_length=255),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default=True, null=True, upload_to='media/brand_imgs/'),
        ),
    ]
