# Generated by Django 5.1.5 on 2025-04-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_brand_shop_brand_name_c466ec_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidorder',
            name='payment_status',
            field=models.CharField(choices=[('Cash on Delevery', 'Cash on Delevery'), ('Khalti', 'Khalti')], default='Cash on Delevery', max_length=255),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='shop_brand_name_c466ec_idx'),
        ),
    ]
