# Generated by Django 5.1.5 on 2025-04-09 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_bidorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidorder',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_order', to='shop.auction'),
        ),
        migrations.AlterField(
            model_name='bidorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
