# Generated by Django 5.1.5 on 2025-04-10 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_bidorder_auction_alter_bidorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidorder',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop.auction'),
        ),
        migrations.AlterField(
            model_name='bidorder',
            name='payment_status',
            field=models.CharField(choices=[('Cash on Delevery', 'Cash on Delevery'), ('Khalti', 'Khalti')], default='Khalti', max_length=255),
        ),
        migrations.AlterField(
            model_name='bidorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
