# Generated by Django 5.1.5 on 2025-04-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_bidorder_auction_alter_bidorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidorder',
            name='payment_status',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('Cash on Delevery', 'Cash on Delevery')], default='Khalti', max_length=255),
        ),
    ]
