# Generated by Django 5.1.6 on 2025-02-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_kyc_verified_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('id_card', 'ID Card'), ('driving_license', 'Driving License'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
